# Generated by Django 3.0.4 on 2020-04-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('http_url', models.CharField(max_length=256, verbose_name='路径')),
            ],
        ),
    ]
